import{a as E,S as q,i as a}from"./assets/vendor-CNqCr-V-.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))f(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const l of o.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&f(l)}).observe(document,{childList:!0,subtree:!0});function r(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function f(t){if(t.ep)return;t.ep=!0;const o=r(t);fetch(t.href,o)}})();const x="53365329-1bc1d5d35bf6bdc5eb7b3c976",P="https://pixabay.com/api/";async function h(s,e=1){try{return(await E.get(P,{params:{key:x,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:e}})).data}catch(r){throw r}}const y=document.querySelector(".gallery"),m=document.querySelector(".loader"),p=document.querySelector(".load-more"),$=new q(".gallery a",{captionsData:"alt",captionDelay:250});function g(s){const e=s.map(r=>`
      <li class="photo-card">
        <a class="link" href="${r.largeImageURL}">
          <img class="gallery-image" src="${r.webformatURL}" alt="${r.tags}" loading="lazy" />
        </a>
        <div class="info">
          <p class="text">Likes</br> ${r.likes}</p>
          <p class="text">Views</br> ${r.views}</p>
          <p class="text">Comments</br> ${r.comments}</p>
          <p class="text">Downloads</br> ${r.downloads}</p>
        </div>
      </li>
    `).join("");y.insertAdjacentHTML("beforeend",e),$.refresh()}function M(){y.innerHTML=""}function b(){m.classList.remove("hidden")}function L(){m.classList.add("hidden")}function v(){p.classList.remove("hidden")}function d(){p.classList.add("hidden")}const w=document.querySelector(".form"),c=w.querySelector('input[name="search-text"]'),H=document.querySelector(".load-more");let u="",n=1,i=0;const S=15;w.addEventListener("submit",async s=>{if(s.preventDefault(),c.value.trim()===""){a.error({title:"Error",message:"Please enter a search query"});return}u=c.value.trim(),n=1,M(),d(),b();try{const e=await h(u,n);if(i=e.totalHits,e.hits.length===0){a.error({title:"Error",message:"Sorry, there is not result"});return}g(e.hits),c.value="",i>n*S?v():(a.info({title:"Info",message:"We're sorry, but you've reached the end of search results"}),d())}catch{a.error({title:"Error",message:"Sorry, there is a problem"})}finally{L()}});H.addEventListener("click",async()=>{n+=1,b();try{const e=await h(u,n);if(i=e.totalHits,e.hits.length===0){a.error({title:"Error",message:"Sorry, there is not result"});return}g(e.hits),i<=n*S?(d(),a.info({title:"Info",message:"We're sorry, but you've reached the end of search results"})):v()}catch{a.error({title:"Error",message:"Sorry, there is a problem"})}finally{L()}const{height:s}=document.querySelector(".gallery .photo-card").getBoundingClientRect();window.scrollBy({top:s*2,behavior:"smooth"})});
//# sourceMappingURL=index.js.map
